# .github/dependabot.yml
version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'monthly'
    commit-message:
      prefix: chore(deps)
      prefix-development: chore(deps)
    open-pull-requests-limit: 1
